version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'nestjs'
      MYSQL_PASSWORD: 'qwerty'
      MYSQL_ROOT_PASSWORD: 'qwerty'
    container_name: nestjs-db
    volumes:
      - ./mysql:/var/lib/mysql