POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "andresjch2804@gmail.com",
  "password": "d!3fEU3hsa"
}

> {%
  client.global.set("auth_token", response.body.token);
%}

###
POST http://localhost:3000/api/auth/me
Authorization: Bearer {{ auth_token }}
