GET {{api_url}}/api/purchase-orders
Authorization: Bearer {{ auth_token }}

###
POST {{api_url}}/api/purchase-orders
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "requisition_id": "f2d72dea-6d22-405b-94b5-41678b734c92",
  "order_number": "002",
  "reception_date": "2023-01-01"
}

###
GET {{api_url}}/api/purchase-orders/requisition-sub-budget
Authorization: Bearer {{ auth_token }}

###
POST {{api_url}}/api/purchase-orders/requisition-sub-budget
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "requisition_id": "341df85f-396c-4f21-94ba-c9772bbc6080",
  "order_number": "999",
  "reception_date": "2023-01-01"
}

###
PATCH {{api_url}}/api/purchase-orders/e9a08351-1c9a-43f9-9057-3083f67db780
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "requisition_id": "dab1fecb-78ae-4b08-91c3-4028313ef2b7",
  "order_number": "001",
  "reception_date": "2023-02-02"
}

###
DELETE {{api_url}}/api/purchase-orders/58ee9118-3832-4f3a-bbe4-6f3e2b6a22f5?requisitionType=RequisitionEntity
Authorization: Bearer {{ auth_token }}

###
DELETE {{api_url}}/api/purchase-orders/18d2c3bc-3d23-499d-b069-fe90318e7a4b?requisitionType=RequisitionSubBudgetEntity
Authorization: Bearer {{ auth_token }}
